- name: make sure twilio is installed
  tags: [twilio]
  become: yes
  apt:
    name: python3-twilio
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install Mixpanel credentials into mixpanel_settings.py
  tags: [twilio]
  template:
    src: twilio_settings.py
    dest: "{{ django_dir }}/lampisite/twilio_settings.py"
    force: yes