- name: install python3 and pip3
  become: True
  apt:
    name: ['python3', 'python3-pip']
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install requests python library
  pip:
    name: requests
    executable: pip3
    extra_args: --upgrade
